<!-- Copyright 2026 上海如静知华信息科技有限公司 · https://www.zhuatech.cn/ -->
<script setup>
import {computed,onMounted,reactive,ref} from 'vue'
import {api,setCredentials} from './api'
import RuleWorkbench from './components/RuleWorkbench.vue'
import RecordToolbar from './components/RecordToolbar.vue'
const credentials=reactive({username:'admin',password:'admin123'}),loggedIn=ref(false),loading=ref(false),error=ref('')
const catalog=ref(null),dashboard=ref(null),records=ref([]),audits=ref([]),controls=ref([]),enterpriseSummary=ref(null),settings=reactive({}),page=ref('dashboard'),moduleCode=ref('')
const showModal=ref(false),editingId=ref(null),form=reactive({recordNo:'',module:'',title:'',businessParty:'',owner:'',amount:0,quantity:1,dueDate:'2026-09-30',riskLevel:'正常',description:''})
const showControlModal=ref(false),controlForm=reactive({controlNo:'ENT-YMS-'+Date.now(),organizationCode:'ZH-SH',fiscalPeriod:'2026-08',controlType:'YARD_CONTROL',subjectNo:'',subjectName:'',assignee:'',riskLevel:'正常',dueDate:'2026-09-30',externalSystem:'WMS',externalRef:'',idempotencyKey:''})
const activeModule=computed(()=>catalog.value?.modules.find(item=>item.code===moduleCode.value))
const money=value=>new Intl.NumberFormat('zh-CN',{style:'currency',currency:'CNY',maximumFractionDigits:0}).format(value||0)
async function login(){loading.value=true;error.value='';try{setCredentials(credentials.username,credentials.password);await loadCore();loggedIn.value=true}catch(e){error.value=e.message}finally{loading.value=false}}
async function loadCore(){[catalog.value,dashboard.value]=await Promise.all([api.catalog(),api.dashboard()]);await openDashboard()}
async function openDashboard(){page.value='dashboard';moduleCode.value='';dashboard.value=await api.dashboard()}
async function openModule(code){page.value='records';moduleCode.value=code;records.value=await api.records(code)}
async function openAudit(){page.value='audit';audits.value=await api.audits()}
async function openSettings(){page.value='settings';Object.assign(settings,await api.settings())}
async function openEnterprise(){page.value='enterprise';moduleCode.value='';[controls.value,enterpriseSummary.value]=await Promise.all([api.enterpriseControls(),api.enterpriseSummary()])}
function resetControl(){Object.assign(controlForm,{controlNo:'ENT-YMS-'+Date.now(),organizationCode:'ZH-SH',fiscalPeriod:new Date().toISOString().slice(0,7),controlType:'YARD_CONTROL',subjectNo:'',subjectName:'',assignee:credentials.username,riskLevel:'正常',dueDate:'2026-09-30',externalSystem:'WMS',externalRef:'',idempotencyKey:'ui-yms-'+crypto.randomUUID()});showControlModal.value=true}
async function saveControl(){try{await api.createEnterprise(controlForm);showControlModal.value=false;await openEnterprise()}catch(e){error.value=e.message}}
async function controlAction(item,action){if(!confirm(`确认执行 ${action}？`))return;try{if(action==='提交')await api.submitEnterprise(item.id);if(action==='批准')await api.reviewEnterprise(item.id,'APPROVE');if(action==='驳回')await api.reviewEnterprise(item.id,'REJECT');if(action==='登记凭证')await api.registerEnterpriseDocument(item.id);if(action==='办结')await api.completeEnterprise(item.id);if(action==='同步')await api.syncEnterprise(item.id);await openEnterprise()}catch(e){error.value=e.message}}
function resetForm(){Object.assign(form,{recordNo:'YMS-'+Date.now(),module:moduleCode.value||catalog.value.modules[0].code,title:'',businessParty:'',owner:'',amount:0,quantity:1,dueDate:'2026-09-30',riskLevel:'正常',description:''});editingId.value=null;showModal.value=true}
function edit(item){Object.assign(form,{recordNo:item.recordNo,module:item.module,title:item.title,businessParty:item.businessParty,owner:item.owner,amount:item.amount,quantity:item.quantity,dueDate:item.dueDate,riskLevel:item.riskLevel,description:item.description});editingId.value=item.id;showModal.value=true}
async function save(){try{if(editingId.value)await api.update(editingId.value,form);else await api.create(form);showModal.value=false;await openModule(form.module)}catch(e){error.value=e.message}}
async function act(item,action){if(!confirm(`确认执行“${action.label}”？`))return;try{await api.action(item.id,action.code,action.label);await openModule(item.module)}catch(e){error.value=e.message}}
async function remove(item){if(!confirm(`确认删除 ${item.recordNo}？`))return;try{await api.remove(item.id);await openModule(item.module)}catch(e){error.value=e.message}}
async function saveSettings(){try{Object.assign(settings,await api.saveSettings(settings));alert('设置已保存')}catch(e){error.value=e.message}}
const actionsFor=item=>catalog.value?.actions.filter(action=>action.from.includes(item.status))||[]
onMounted(()=>{})
</script>
<template>
<div v-if="!loggedIn" class="login-page"><section class="brand-panel"><div class="eyebrow">ZHUATECH · ENTERPRISE SOFTWARE</div><h1>知华科技<br>园区与月台管理 YMS</h1><p>让车辆、门岗、月台和装卸资源在同一节奏下协同</p><a href="https://www.zhuatech.cn/">www.zhuatech.cn</a></section><form class="login-card" @submit.prevent="login"><span class="product-mark">Yms</span><h2>进入业务工作台</h2><label>账号<input v-model="credentials.username" autocomplete="username"></label><label>密码<input v-model="credentials.password" type="password" autocomplete="current-password"></label><p class="error" v-if="error">{{error}}</p><button :disabled="loading">{{loading?'正在连接':'登录系统'}}</button><small>演示账号：admin admin123 / 业务人员 operator123</small></form></div>
  <div v-else class="shell">
    <aside><div class="logo"><b>ZH</b><span>知华科技<small>Enterprise V2.0</small></span></div><nav><button :class="{active:page==='dashboard'}" @click="openDashboard">运营总览</button><p>业务模块</p><button v-for="item in catalog.modules" :key="item.code" :class="{active:moduleCode===item.code}" @click="openModule(item.code)">{{item.name}}</button><button :class="{active:page==='rules'}" @click="page='rules';moduleCode=''">领域规则验证</button><p>企业治理</p><button :class="{active:page==='enterprise'}" @click="openEnterprise">企业控制中心</button><button :class="{active:page==='audit'}" @click="openAudit">操作审计</button><button :class="{active:page==='settings'}" @click="openSettings">系统设置</button></nav><footer>上海如静知华信息科技有限公司<br><a href="https://www.zhuatech.cn/">知华科技官网</a></footer></aside>
    <main><header><div><span class="eyebrow">车辆预约、门岗、排队、月台调度、称重、装卸、异常与计费</span><h2>{{page==='dashboard'?'运营总览':activeModule?.name||({rules:'领域规则验证',enterprise:'企业控制中心',audit:'操作审计',settings:'系统设置'}[page])}}</h2></div><div class="user">{{credentials.username}}<button @click="loggedIn=false">退出</button></div></header><p class="error global" v-if="error" @click="error=''">{{error}} ×</p>
      <template v-if="page==='dashboard'&&dashboard"><section class="hero"><div><span>今日工作面</span><h1>让车辆、门岗、月台和装卸资源在同一节奏下协同</h1><p>{{catalog.scene}}</p></div><button @click="openModule(catalog.modules[0].code)">进入业务台账</button></section><section class="metrics"><article><span>业务记录</span><b>{{dashboard.totalRecords}}</b></article><article><span>关联金额</span><b>{{money(dashboard.totalAmount)}}</b></article><article><span>业务模块</span><b>{{catalog.modules.length}}</b></article><article><span>风险关注</span><b>{{dashboard.recentRecords.filter(i=>i.riskLevel!=='正常').length}}</b></article></section><section class="grid"><article class="panel"><div class="panel-title"><h3>模块运行情况</h3></div><div v-for="item in catalog.modules" :key="item.code" class="module-row" @click="openModule(item.code)"><div><b>{{item.name}}</b><small>{{item.description}}</small></div><span>{{dashboard.moduleCounts[item.code]||0}}</span></div></article><article class="panel"><div class="panel-title"><h3>最近业务</h3></div><div v-for="item in dashboard.recentRecords" :key="item.id" class="recent"><span :class="['status',item.riskLevel==='正常'?'ok':'warn']">{{item.status}}</span><div><b>{{item.title}}</b><small>{{item.recordNo}} · {{item.owner}}</small></div></div></article></section></template>
      <template v-else-if="page==='records'"><section class="module-intro"><div><span>{{activeModule?.code}}</span><h3>{{activeModule?.name}}</h3><p>{{activeModule?.description}}</p></div><button @click="resetForm">+ 新建记录</button></section><RecordToolbar :module="moduleCode" @loaded="records=$event" /><section class="panel table-panel"><table><thead><tr><th>业务编号</th><th>事项</th><th>{{catalog.partyLabel}}</th><th>{{catalog.amountLabel}}</th><th>责任人</th><th>状态</th><th>{{catalog.dueLabel}}</th><th>操作</th></tr></thead><tbody><tr v-for="item in records" :key="item.id"><td><code>{{item.recordNo}}</code></td><td><b>{{item.title}}</b><small>{{item.description}}</small></td><td>{{item.businessParty}}</td><td>{{money(item.amount)}}</td><td>{{item.owner}}</td><td><span :class="['status',item.riskLevel==='正常'?'ok':'warn']">{{item.status}}</span></td><td>{{item.dueDate}}</td><td class="actions"><button v-for="action in actionsFor(item)" :key="action.code" @click="act(item,action)">{{action.label}}</button><button v-if="item.status===catalog.initialStatus" @click="edit(item)">编辑</button><button v-if="item.status===catalog.initialStatus" class="danger" @click="remove(item)">删除</button></td></tr></tbody></table></section></template>
      <template v-else-if="page==='rules'"><RuleWorkbench /></template>
      <template v-else-if="page==='enterprise'"><section class="module-intro"><div><span>ENTERPRISE CONTROL</span><h3>企业控制中心</h3><p>按组织与账期管理关键事项，覆盖幂等提交、职责分离、凭证完整性、办结和外部系统回执。</p></div><button @click="resetControl">+ 新建控制项</button></section><section v-if="enterpriseSummary" class="metrics"><article><span>控制项</span><b>{{enterpriseSummary.total}}</b></article><article><span>已逾期</span><b>{{enterpriseSummary.overdue}}</b></article><article><span>待复核</span><b>{{enterpriseSummary.states.PENDING_REVIEW||0}}</b></article><article><span>同步成功</span><b>{{enterpriseSummary.syncStates.SYNCED||0}}</b></article></section><section class="panel table-panel"><table><thead><tr><th>控制单号</th><th>组织 / 期间</th><th>业务对象</th><th>责任人</th><th>状态</th><th>凭证 / 同步</th><th>操作</th></tr></thead><tbody><tr v-for="item in controls" :key="item.id"><td><code>{{item.controlNo}}</code><small>{{item.controlType}}</small></td><td>{{item.organizationCode}}<small>{{item.fiscalPeriod}}</small></td><td><b>{{item.subjectName}}</b><small>{{item.subjectNo}}</small></td><td>{{item.assignee}}</td><td><span :class="['status',item.state==='COMPLETED'?'ok':'warn']">{{item.state}}</span></td><td>{{item.documentCount}} 份<small>{{item.syncState}}</small></td><td class="actions"><button v-if="item.state==='DRAFT'" @click="controlAction(item,'提交')">提交</button><button v-if="item.state==='PENDING_REVIEW'&&credentials.username==='admin'" @click="controlAction(item,'批准')">批准</button><button v-if="item.state==='PENDING_REVIEW'&&credentials.username==='admin'" class="danger" @click="controlAction(item,'驳回')">驳回</button><button v-if="item.state==='APPROVED'&&item.documentCount===0" @click="controlAction(item,'登记凭证')">登记凭证</button><button v-if="item.state==='APPROVED'&&item.documentCount>0" @click="controlAction(item,'办结')">办结</button><button v-if="['APPROVED','COMPLETED'].includes(item.state)&&credentials.username==='admin'" @click="controlAction(item,'同步')">同步</button></td></tr></tbody></table></section></template>
<template v-else-if="page==='audit'"><section class="panel table-panel"><table><thead><tr><th>时间</th><th>模块</th><th>动作</th><th>业务编号</th><th>操作人</th><th>说明</th></tr></thead><tbody><tr v-for="item in audits" :key="item.id"><td>{{item.occurredAt?.replace('T',' ').slice(0,19)}}</td><td>{{item.module}}</td><td>{{item.action}}</td><td>{{item.businessNo}}</td><td>{{item.operatorName}}</td><td>{{item.detail}}</td></tr></tbody></table></section></template>
      <template v-else-if="page==='settings'"><section class="panel settings"><h3>系统参数</h3><p>配置保存到数据库，重启服务后继续生效。</p><label v-for="(_,key) in settings" :key="key">{{key}}<input v-model="settings[key]"></label><button @click="saveSettings">保存设置</button></section></template>
    </main>
  </div>
  <div v-if="showModal" class="modal" @click.self="showModal=false"><form class="modal-card" @submit.prevent="save"><div class="panel-title"><h3>{{editingId?'编辑':'新建'}}业务记录</h3><button type="button" @click="showModal=false">×</button></div><div class="form-grid"><label>业务编号<input v-model="form.recordNo" :disabled="editingId" required></label><label>模块<select v-model="form.module"><option v-for="item in catalog.modules" :value="item.code">{{item.name}}</option></select></label><label class="wide">事项名称<input v-model="form.title" required></label><label>{{catalog.partyLabel}}<input v-model="form.businessParty" required></label><label>责任人<input v-model="form.owner" required></label><label>{{catalog.amountLabel}}<input v-model.number="form.amount" type="number" min="0"></label><label>{{catalog.quantityLabel}}<input v-model.number="form.quantity" type="number" min="0"></label><label>{{catalog.dueLabel}}<input v-model="form.dueDate" type="date" required></label><label>风险<select v-model="form.riskLevel"><option>正常</option><option>关注</option><option>高风险</option></select></label><label class="wide">说明<textarea v-model="form.description" rows="3"></textarea></label></div><button class="primary">保存记录</button></form></div>
  <div v-if="showControlModal" class="modal" @click.self="showControlModal=false"><form class="modal-card" @submit.prevent="saveControl"><div class="panel-title"><h3>新建企业控制项</h3><button type="button" @click="showControlModal=false">×</button></div><div class="form-grid"><label>控制单号<input v-model="controlForm.controlNo" required></label><label>组织代码<input v-model="controlForm.organizationCode" required></label><label>账期<input v-model="controlForm.fiscalPeriod" type="month" required></label><label>控制类型<input v-model="controlForm.controlType" required></label><label>业务对象编号<input v-model="controlForm.subjectNo" required></label><label>责任人<input v-model="controlForm.assignee" required></label><label class="wide">业务对象名称<input v-model="controlForm.subjectName" required></label><label>到期日<input v-model="controlForm.dueDate" type="date" required></label><label>风险<select v-model="controlForm.riskLevel"><option>正常</option><option>关注</option><option>高风险</option></select></label><label>外部系统<input v-model="controlForm.externalSystem"></label><label>外部引用<input v-model="controlForm.externalRef"></label></div><button class="primary">保存控制项</button></form></div>
</template>
